kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-terminator
  namespace: dogfooding
subjects:
- kind: ServiceAccount
  name: pod-terminator
  namespace: dogfooding
roleRef:
  kind: Role
  name: pod-terminator
  apiGroup: ""
